name: Release

on:
  push:
    branches: [ main ]

jobs:
  windows:
    name: "Windows x64 (latest)"
    runs-on: windows-latest

    steps:
    - name: Downloading Qt 5.15.2
      run: pacman -S mingw-w64-i686-qt5-static
      shell: bash