name: Release

on:
  push:
    branches: [ main ]

jobs:
  windows:
    name: "Windows x64 (latest)"
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Installing Qt Creator
      uses: jurplel/install-qt-action@v2
      with:
        arch: 'win64_mingw81'

    - name: Download sources of Qt 5.15.2
      run: |
        curl -LO https://download.qt.io/official_releases/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.zip
        7z x qt-everywhere-src-5.15.2.zip -oqt5

    - name: Patch qmake.conf
      run: |
        cd ./qt5/qt-everywhere-src-5.15.2/qtbase/mkspecs/win32-g++/
        echo QMAKE_LFLAGS += -static -static-libgcc >> qmake.conf
        echo QMAKE_CFLAGS_RELEASE -= -O2 >> qmake.conf
        echo QMAKE_CFLAGS_RELEASE += -Os -momit-leaf-frame-pointer >> qmake.conf
        echo DEFINES += QT_STATIC_BUILD >> qmake.conf

    - name: Configure
      run: | 
        cd ./qt5/qt-everywhere-src-5.15.2
        ./configure.bat -static -release -platform win32-g++ -opensource -confirm-license -prefix "../mingw32-x64-qt-static" -qt-zlib -qt-libpng -qt-webp -qt-libjpeg -qt-freetype -no-opengl -skip qt3d -skip qtactiveqt -skip qtandroidextras -skip qtcharts -skip qtconnectivity -skip qtdatavis3d -skip qtdeclarative -skip qtdoc -skip qtgamepad -skip qtlocation -skip qtlottie -skip qtmacextras -skip qtmultimedia -skip qtnetworkauth -skip qtpurchasing -skip qtquick3d -skip qtquickcontrols -skip qtquickcontrols2 -skip qtquicktimeline -skip qtremoteobjects -skip qtscript -skip qtsensors -skip qtspeech -skip qtsvg -skip qtwayland -skip qtwebglplugin -skip qtwebview -skip webengine -make libs -nomake tools -nomake examples -nomake tests

    - name: Build Qt 5.15.2 static
      run: |
        cd ./qt5/qt-everywhere-src-5.15.2
        mingw32-make -j4
        mingw32-make install

    - name: Deploy
      run: |
        cd qt5
        7z a mingw32-x64-qt-static.zip ./mingw32-x64-qt-static

    - name: Upload Qt 5.15.2 static
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./qt5/mingw32-x64-qt-static.zip
        token: ${{ secrets.ACCESS_TOKEN }}
        commit: main
        tag: mingw32-x64-qt-5.15.2-static

  linux:
    name: "Ubuntu x64 (latest)"
    runs-on: ubuntu-latest

    steps:
    - name: Installing Qt Creator
      uses: jurplel/install-qt-action@v2

    - name: Download sources of Qt 5.15.2
      run: |
        curl -LO https://download.qt.io/official_releases/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.tar.xz
        mkdir qt5
        tar -xvf qt-everywhere-src-5.15.2.tar.xz -C ./qt5

    # - name: Patch qmake.conf
    #   run: |
    #     cd ./qt5/qt-everywhere-src-5.15.2/qtbase/mkspecs/win32-g++/
    #     echo QMAKE_LFLAGS += -static -static-libgcc >> qmake.conf
    #     echo QMAKE_CFLAGS_RELEASE -= -O2 >> qmake.conf
    #     echo QMAKE_CFLAGS_RELEASE += -Os -momit-leaf-frame-pointer >> qmake.conf
    #     echo DEFINES += QT_STATIC_BUILD >> qmake.conf

    - name: Configure
      run: |
        cd ./qt5/qt-everywhere-src-5.15.2/
        ./configure -static -release -platform linux-g++ -opensource -confirm-license -prefix "../gcc-x64-qt-static" -qt-zlib -qt-libpng -qt-webp -qt-libjpeg -qt-freetype -no-opengl -skip qt3d -skip qtactiveqt -skip qtandroidextras -skip qtcharts -skip qtconnectivity -skip qtdatavis3d -skip qtdeclarative -skip qtdoc -skip qtgamepad -skip qtlocation -skip qtlottie -skip qtmacextras -skip qtmultimedia -skip qtnetworkauth -skip qtpurchasing -skip qtquick3d -skip qtquickcontrols -skip qtquickcontrols2 -skip qtquicktimeline -skip qtremoteobjects -skip qtscript -skip qtsensors -skip qtspeech -skip qtsvg -skip qtwayland -skip qtwebglplugin -skip qtwebview -skip webengine -make libs -nomake tools -nomake examples -nomake tests

    - name: Build Qt 5.15.2 static
      run: |
        cd ./qt5/qt-everywhere-src-5.15.2
        make -j4
        make install

    - name: Deploy
      run: |
        cd qt5
        tar -czvf gcc-x64-qt-static.tar.gz ./gcc-x64-qt-static

    - name: Upload Qt 5.15.2 static
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./qt5/gcc-x64-qt-static.zip
        token: ${{ secrets.ACCESS_TOKEN }}
        commit: main
        tag: gcc-x64-qt-5.15.2-static