name: Release

on:
  push:
    branches: [ main ]

jobs:
  windows:
    name: "Windows x64 (latest)"
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Installing MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: | 
          mingw-w64-i686-qt5-static 
          mingw-w64-i686-toolchain 
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make

    - name: Checking build system
      run: |
        D:/a/_temp/msys64/mingw32/qt5-static/bin/qmake.exe -v
        mingw-w64-x86_64-make -v