name: Release

on:
  push:
    branches: [ main ]

jobs:
  windows:
    name: "Windows x64 (latest)"
    runs-on: windows-latest

    steps:
    - name: Installation Qt 5.15.2
      uses: jurplel/install-qt-action@v2.13.2
      with:
        arch: win64_mingw81

    - name: Download source code
      run: | 
        curl -LO https://download.qt.io/official_releases/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.zip
        7z e qt-everywhere-src-5.15.2.zip -oqt5
      shell: bash

    - name: Configure Qt
      run: |
        cd qt5
        ./configure -static -release -platform win32-g++ \ 
        -prefix "../qtstatic" \
        -qt-zlib \
        -qt-libpng \
        -qt-libjpeg \
        -qt-freetype \ 
        -skip qt3d \
        -skip qtdatavis3d \
        -skip qtdoc \
        -skip qtgamepad \
        -skip qtquick3d \ 
        -nomake tools \
        -nomake tests \
        -nomake examples \
        -no-dbus \
        -no-ssl \
        -no-pch \
        -opensource \
        -confirm-license
      shell: bash

    - name: Build Qt static
      run: | 
        cd qt5
        mingw32-make -j4
      shell: bash

    - name: Archive build
      run: 7z a qtstatic-widnows-x64.zip .\qtstatic\
      shell: bash


    - name: Upload artifacts
      uses: ncipollo/release-action@v1
      with:
        artifacts: qtstatic-widnows-x64.zip
        token: ${{ secrets.ACCESS_TOKEN }}
        commit: main
        tag: windows-x64