name: Release

on:
  push:
    branches: [ main ]

jobs:
  windows:
    name: "Windows x64 (latest)"
    runs-on: windows-latest

    steps:
    - name: Download Qt 5.15.2
      run: git clone https://code.qt.io/qt/qt5.git -b 5.15.2
      shell: bash

    - name: Build Qt static
      run: |
        cd qt5
        ./init-repository -f --module-subset=qtbase
        ./configure -static -release -prefix "../qtstatic" \ 
                            -qt-zlib \
                            -qt-libpng \
                            -qt-libjpeg \
                            -qt-freetype \
                            -no-opengl \
                            -skip qt3d \
                            -skip qtactiveqt \
                            -skip qtandroidextras \
                            -skip qtcharts \
                            -skip qtconnectivity \
                            -skip qtdatavis3d \ 
                            -skip qtdeclarative \
                            -skip qtdoc \
                            -skip qtgamepad \
                            -skip qtlocation \
                            -skip qtlottie \
                            -skip qtmacextras \
                            -skip qtmultimedia \
                            -skip qtnetworkauth \
                            -skip qtpurchasing \
                            -skip qtquick3d \
                            -skip qtquickcontrols \
                            -skip qtquickcontrols2 \
                            -skip qtquicktimeline \
                            -skip qtremoteobjects \
                            -skip qtscript \
                            -skip qtsensors \
                            -skip qtspeech \
                            -skip qtsvg \
                            -skip qtwayland \
                            -skip qtwebglplugin \
                            -skip qtwebview \
                            -skip webengine \
                            -nomake tools \
                            -nomake tests \
                            -nomake examples \
                            -no-dbus \
                            -no-ssl \
                            -no-pch \
                            -opensource \
                            -confirm-license
        make -j4 && make install
      shell: bash

    - name: Archive build
      run: 7z a qtstatic-widnows-x64.zip .\qtstatic\
      shell: bash


    - name: Upload artifacts
      uses: ncipollo/release-action@v1
      with:
        artifacts: qtstatic-widnows-x64.zip
        token: ${{ secrets.ACCESS_TOKEN }}
        commit: main
        tag: windows-x64